name: Robot Pertama

on: workflow_dispatch

jobs:
  menyapa:
    runs-on: ubuntu-latest
    steps:
      - name: Sebelum mengambil kode
        run: ls -la

      - name: Ambil kode dari repositori
        uses: actions/checkout@v4

      - name: Sesudah mengambil kode
        run: ls -la
