name: Robot Pertama

on:
  push:
  workflow_dispatch:

jobs:
  menyapa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Info tentang pemicunya
        run: |
          echo "Robot ini dibangunkan oleh: ${{ github.event_name }}"
          echo "Di branch: ${{ github.ref_name }}"
          echo "Oleh pengguna: ${{ github.actor }}"
