name: Robot Bersama

on:
  workflow_call:
    inputs:
      nama-proyek:
        type: string
        required: true

jobs:
  bekerja:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v99
      - run: echo "${{ inputs.nama-proyek }}"
